image: Visual Studio 2017
configuration: Release
before_build:
- cmd: dotnet restore
build:
  project: DidacticalEnigma.sln
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
