image: Visual Studio 2017
configuration: Release
build:
  project: DidacticalEnigma.sln
  verbosity: minimal
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - nuget restore
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

