image: Visual Studio 2017
configuration: Release
build:
  project: DidacticalEnigma.sln
  verbosity: minimal
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - nuget restore
after_build:
  - ren %APPVEYOR_BUILD_FOLDER%\DidacticalEnigma\bin\Release DidacticalEnigma
  - 7z a -r DidacticalEnigma.zip %APPVEYOR_BUILD_FOLDER%\DidacticalEnigma\bin\DidacticalEnigma
artifacts:
  - path: DidacticalEnigma.zip
    name: Full program
    type: zip

