image: Visual Studio 2017
configuration: Release
build:
  project: DidacticalEnigma.sln
  verbosity: minimal
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - nuget restore
artifacts:
  - path: DidacticalEnigma/bin/Release/*
    name: Release
    type: zip

