image:
  - Visual Studio 2022
  - Ubuntu
configuration: Release
install:
  - ps: cd $env:APPVEYOR_BUILD_FOLDER
  - git submodule update --init --recursive
build_script:
  - ps: dotnet nuget add source $env:APPVEYOR_BUILD_FOLDER/OutputNuget
  - ps: dotnet pack TinyIndex/TinyIndex/TinyIndex.csproj -c Release -o $env:APPVEYOR_BUILD_FOLDER/OutputNuget
  - ps: dotnet pack DidacticalEnigma.Core/Utility/Utility.csproj -c Release -o $env:APPVEYOR_BUILD_FOLDER/OutputNuget
  - ps: dotnet pack DidacticalEnigma.Core/JDict/JDict.csproj -c Release -o $env:APPVEYOR_BUILD_FOLDER/OutputNuget
  - ps: dotnet pack DidacticalEnigma.Core/DidacticalEnigma.Core/DidacticalEnigma.Core.csproj -c Release -o $env:APPVEYOR_BUILD_FOLDER/OutputNuget
  - ps: dotnet pack DidacticalEnigma.Core/DidacticalEnigma.IoCModule/DidacticalEnigma.IoCModule.csproj -c Release -o $env:APPVEYOR_BUILD_FOLDER/OutputNuget
  - ps: dotnet pack DidacticalEnigma.Project/DidacticalEnigma.Project/DidacticalEnigma.Project.csproj -c Release -o $env:APPVEYOR_BUILD_FOLDER/OutputNuget
  - ps: dotnet pack DidacticalEnigma.Project/DidacticalEnigma.MagicTranslatorProject/DidacticalEnigma.MagicTranslatorProject.csproj -c Release -o $env:APPVEYOR_BUILD_FOLDER/OutputNuget
  - ps: dotnet pack DidacticalEnigma.Misc/DidacticalEnigma.Updater/DidacticalEnigma.Updater.csproj -c Release -o $env:APPVEYOR_BUILD_FOLDER/OutputNuget
  - ps: dotnet pack DidacticalEnigma.Misc/DidacticalEnigma.Mem.Client/DidacticalEnigma.Mem.Client.csproj -c Release -o $env:APPVEYOR_BUILD_FOLDER/OutputNuget
  - ps: dotnet pack DidacticalEnigma.Misc/DidacticalEnigma.Mem.DataSource/DidacticalEnigma.Mem.DataSource.csproj -c Release -o $env:APPVEYOR_BUILD_FOLDER/OutputNuget
  - ps: dotnet pack DidacticalEnigma.Misc/DidacticalEnigma.IronPython/DidacticalEnigma.IronPython.csproj -c Release -o $env:APPVEYOR_BUILD_FOLDER/OutputNuget
  - ps: dotnet pack clipwatch/ClipwatchSharp/ClipwatchSharp/ClipwatchSharp.csproj -c Release -o $env:APPVEYOR_BUILD_FOLDER/OutputNuget
  - ps: dotnet pack webview_csharp/src/SharpWebview/SharpWebview.csproj -c Release -o $env:APPVEYOR_BUILD_FOLDER/OutputNuget
  - ps: if($isWindows) { nuget restore; }
  - ps: dotnet publish DidacticalEnigma.Misc/MagicTranslatorGlosser/MagicTranslatorGlosser.csproj -c Release -r linux-x64 --self-contained false -o $env:APPVEYOR_BUILD_FOLDER/Output/DidacticalEnigma
  - ps: dotnet publish DidacticalEnigma.Misc/MagicTranslatorGlosser/MagicTranslatorGlosser.csproj -c Release -r win-x64 --self-contained false -o $env:APPVEYOR_BUILD_FOLDER/Output/DidacticalEnigma
  - ps: dotnet publish DidacticalEnigma.Next/DidacticalEnigma.Next/DidacticalEnigma.Next.csproj -c Release -r linux-x64 --self-contained false -o $env:APPVEYOR_BUILD_FOLDER/Output/DidacticalEnigma
  - ps: dotnet publish DidacticalEnigma.Next/DidacticalEnigma.Next/DidacticalEnigma.Next.csproj -c Release -r win-x64 --self-contained false -o $env:APPVEYOR_BUILD_FOLDER/Output/DidacticalEnigma
  - ps: if($isWindows) { dotnet publish DidacticalEnigma.Updater.WPF/DidacticalEnigma.Updater.WPF.csproj -c Release -r win-x64 --self-contained false -o $env:APPVEYOR_BUILD_FOLDER/Output/DidacticalEnigma }
  - ps: if($isWindows) { dotnet publish DidacticalEnigma.WPF/DidacticalEnigma.WPF.csproj -c Release -r win-x64 --self-contained false -o $env:APPVEYOR_BUILD_FOLDER/Output/DidacticalEnigma }
  - ps: if($isLinux) { dotnet build $env:APPVEYOR_BUILD_FOLDER/DidacticalEnigma.Core/AutomatedTests.NetCore/AutomatedTests.NetCore.csproj }
after_build:
  - ps: if($isWindows) { mv $env:APPVEYOR_BUILD_FOLDER/Data $env:APPVEYOR_BUILD_FOLDER/Output/DidacticalEnigma; }
  - ps: if($isWindows) { 7z a -r DidacticalEnigma.zip $env:APPVEYOR_BUILD_FOLDER/Output/DidacticalEnigma; }
artifacts:
  - path: DidacticalEnigma.zip
    name: Full program
    type: zip


for:
-
  matrix:
    only:
      - image: Ubuntu

  test_script:
  - ps: dotnet test $env:APPVEYOR_BUILD_FOLDER/DidacticalEnigma.Core/AutomatedTests.NetCore/AutomatedTests.NetCore.csproj

deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: 'This is the full program, with all the files needed for it to work.'
  provider: GitHub
  auth_token:
    secure: P9IuL8ONTiUNMbvX1z83aFQxCyXkCGa/B8lT9hdASDPrKv6GrAG9iE1Ii61rvhXD
  artifact: DidacticalEnigma.zip
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
    CI_WINDOWS: true

