image: Visual Studio 2017
configuration: Release
build:
  project: DidacticalEnigma.sln
  verbosity: minimal
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - nuget restore
  - dotnet publish MagicTranslatorGlosser/MagicTranslatorGlosser.csproj -c Release -r linux-x64 --self-contained false -o %APPVEYOR_BUILD_FOLDER%\DidacticalEnigma\bin\Release\MagicTranslatorGlosser
  - dotnet publish MagicTranslatorGlosser/MagicTranslatorGlosser.csproj -c Release -r win-x64 --self-contained false -o %APPVEYOR_BUILD_FOLDER%\DidacticalEnigma\bin\Release\MagicTranslatorGlosser
after_build:
  - ren %APPVEYOR_BUILD_FOLDER%\DidacticalEnigma\bin\Release DidacticalEnigma
  - 7z a -r DidacticalEnigma.zip %APPVEYOR_BUILD_FOLDER%\DidacticalEnigma\bin\DidacticalEnigma
artifacts:
  - path: DidacticalEnigma.zip
    name: Full program
    type: zip
deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: 'This is the full program, with all the files needed for it to work.'
  provider: GitHub
  auth_token:
    secure: fzqkckOMapDGnWMt0ZWxBM4k+pxuAQtdO7H4sUj3nqqk65Cm+UYKUf7f6I3AqQIM
  artifact: DidacticalEnigma.zip
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true

