image:
  - Visual Studio 2019
  - Ubuntu
configuration: Release
install:
  - ps: cd $env:APPVEYOR_BUILD_FOLDER
  - git submodule update --init --recursive
build_script:
  - ps: dotnet nuget add source $env:APPVEYOR_BUILD_FOLDER/OutputNuget
  - ps: dotnet pack TinyIndex/TinyIndex.sln -o $env:APPVEYOR_BUILD_FOLDER/OutputNuget
  - ps: dotnet pack DidacticalEnigma.Core/DidacticalEnigma.Core.sln -o $env:APPVEYOR_BUILD_FOLDER/OutputNuget
  - ps: dotnet pack DidacticalEnigma.Project/DidacticalEnigma.Project.sln -o $env:APPVEYOR_BUILD_FOLDER/OutputNuget
  - ps: nuget restore
  - ps: dotnet publish DidacticalEnigma.Misc/MagicTranslatorGlosser/MagicTranslatorGlosser.csproj -c Release -r linux-x64 --self-contained false -o $env:APPVEYOR_BUILD_FOLDER/DidacticalEnigma/bin/Release/MagicTranslatorGlosser
  - ps: dotnet publish DidacticalEnigma.Misc/MagicTranslatorGlosser/MagicTranslatorGlosser.csproj -c Release -r win-x64 --self-contained false -o $env:APPVEYOR_BUILD_FOLDER/DidacticalEnigma/bin/Release/MagicTranslatorGlosser
  - ps: if($isWindows) { msbuild -verbosity:minimal DidacticalEnigma.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"; }
  - ps: if($isLinux) { dotnet build $env:APPVEYOR_BUILD_FOLDER/AutomatedTests.NetCore/AutomatedTests.NetCore.csproj }
after_build:
  - ps: if($isWindows) { mv $env:APPVEYOR_BUILD_FOLDER/DidacticalEnigma/bin/Release $env:APPVEYOR_BUILD_FOLDER/DidacticalEnigma/bin/DidacticalEnigma; }
  - ps: if($isWindows) { 7z a -r DidacticalEnigma.zip $env:APPVEYOR_BUILD_FOLDER/DidacticalEnigma/bin/DidacticalEnigma; }
artifacts:
  - path: DidacticalEnigma.zip
    name: Full program
    type: zip


for:
-
  matrix:
    only:
      - image: Ubuntu

  test_script:
  - ps: dotnet test $env:APPVEYOR_BUILD_FOLDER/DidacticalEnigma.Core/AutomatedTests.NetCore/AutomatedTests.NetCore.csproj

deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: 'This is the full program, with all the files needed for it to work.'
  provider: GitHub
  auth_token:
    secure: fzqkckOMapDGnWMt0ZWxBM4k+pxuAQtdO7H4sUj3nqqk65Cm+UYKUf7f6I3AqQIM
  artifact: DidacticalEnigma.zip
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
    CI_WINDOWS: true

