// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DataSourceParseResponse
    {
        /// <summary>
        /// Initializes a new instance of the DataSourceParseResponse class.
        /// </summary>
        public DataSourceParseResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DataSourceParseResponse class.
        /// </summary>
        public DataSourceParseResponse(string context = default(string), string error = default(string))
        {
            Context = context;
            Error = error;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "context")]
        public string Context { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "error")]
        public string Error { get; set; }

    }
}
