// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class DataSourceParseRequest
    {
        /// <summary>
        /// Initializes a new instance of the DataSourceParseRequest class.
        /// </summary>
        public DataSourceParseRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DataSourceParseRequest class.
        /// </summary>
        public DataSourceParseRequest(IList<string> requestedDataSources = default(IList<string>), string id = default(string), int? position = default(int?))
        {
            RequestedDataSources = requestedDataSources;
            Id = id;
            Position = position;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestedDataSources")]
        public IList<string> RequestedDataSources { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "position")]
        public int? Position { get; set; }

    }
}
