// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ListRadicalsResult
    {
        /// <summary>
        /// Initializes a new instance of the ListRadicalsResult class.
        /// </summary>
        public ListRadicalsResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ListRadicalsResult class.
        /// </summary>
        public ListRadicalsResult(IList<string> possibleRadicals, IList<string> sortingCriteria)
        {
            PossibleRadicals = possibleRadicals;
            SortingCriteria = sortingCriteria;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "possibleRadicals")]
        public IList<string> PossibleRadicals { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sortingCriteria")]
        public IList<string> SortingCriteria { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (PossibleRadicals == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "PossibleRadicals");
            }
            if (SortingCriteria == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "SortingCriteria");
            }
        }
    }
}
